# Generated by Django 4.2.4 on 2024-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=65536)),
            ],
        ),
    ]
