# Generated by Django 4.2.4 on 2024-01-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamestateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.CharField(max_length=4294967296)),
                ('created', models.DateTimeField()),
                ('filename', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MapBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageData', models.CharField(max_length=4294967296)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='sprite',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
