# Generated by Django 4.2.4 on 2024-01-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle15', '0002_gamestatemap_mapbackground_sprite_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprite',
            old_name='image',
            new_name='imageData',
        ),
    ]
