# Generated by Django 4.2.4 on 2023-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stupidpowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stupidpower',
            name='ruling',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stupidpower',
            name='power',
            field=models.CharField(max_length=200),
        ),
    ]
