# Generated by Django 4.2.4 on 2023-08-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stupidpowers', '0002_stupidpower_ruling_alter_stupidpower_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stupidpower',
            name='ruling',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
