# Generated by Django 4.2.4 on 2023-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stupidpowers', '0003_alter_stupidpower_ruling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stupidpower',
            name='ruling',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
